spring:
  application:
    name: Rest2
  security:
    user:
      name: Junior
      password: 123456
      roles: ADMIN
  datasource:
    url: jdbc:postgresql://localhost:5432/TestLesson
    username: 'postgres'
    password: '0000'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
